config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'searches#index'

  resources :searches, only: [:new, :create, :index]
  post 'index', controller: :searches
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/searches_controller.rb
require 'rexml/document'
include REXML
require 'open-uri'

class SearchesController < ApplicationController
  def index
    @search_form = SearchForm.new(q: params[:q])
    @articles = build_my_articles
  end

  def build_my_articles
    per_page = 100
    clear_articles

    if params[:q].present?
      clear_search
      params[:q].delete('')
      term = I18n.transliterate(params[:q].join(' '))
      term = term.tr(' ', '+')

      Eutils::Esearch.articles_pmids_about(term)

      ids = Search.first.description

      paginated_ids = ids[0..per_page]
      Eutils::Efetch.articles_about(paginated_ids, term)

      return if Article.count.zero?

      max_concept_length = params[:search_form][:max_concept_length].to_i || 5

      Article.find_each do |article|
        article.create_keywords!(max_concept_length)
      end

      @suggestions = Keyword.hash_of_grouped_with_weights.first(20).map { |item| item[0] }
    elsif params[:page].present?
      ids = Search.first.description

      paginated_ids = ids[((params[:page].to_i.presence || 0) * per_page)..(params[:page].to_i.presence + 1) * per_page]

      Eutils::Efetch.articles_about(paginated_ids, term)

      return if Article.count.zero?

      max_concept_length = 5

      Article.find_each do |article|
        article.create_keywords!(max_concept_length)
      end

      @suggestions = Keyword.hash_of_grouped_with_weights.first(20).map { |item| item[0] }
    end
    Article.all
  end

  private

  def clear_articles
    Keyword.delete_all
    Article.delete_all
  end

  def clear_search
    Search.delete_all
  end
end

app/views/searches/_form.html.slim
- form_class ||= ''
= form_tag searches_path, class: "#{form_class} dropdown" do
  div.input-group
    /= text_field_tag 'term', '', class: 'form-control', placeholder: 'Start your search here', value: Article.first.try(:term)
    = text_field_tag 'term', '', class: 'form-control', placeholder: 'Start your search here'
    .input-group-btn
      = submit_tag 'Search', class: 'btn btn-primary'

  - if Article.any?
    .btn.btn-default.dropdown-toggle data-toggle="dropdown"
      = fa_icon 'tags fw'
      span.badge = @keywords.try(:length) || 0

    ul.dropdown-menu
      - if @keywords.present?
        - @keywords.each do |keyword|
          li = keyword
      - else
        li: .alert.alert-info Não há tags

app/views/searches/index.html.slim
.search
  h1 Biosearch

  = simple_form_for(@search_form, url: searches_path, method: 'GET') do |f|
    = f.input :q, as: :select, collection: f.object.q, input_html: { class: 'select2-tokenizer', multiple: true, name: 'q[]'}, label: false
    = f.input :max_concept_length, collection: 3..10, include_blank: false, label: "Concepts' max length"

    = f.submit 'search', class: 'btn btn-primary'

.search-filters
  - if @suggestions
    - @suggestions.each do |suggestion|
      .btn.btn-primary data-btn-searchable="" data-value="#{suggestion}"
        i.fa.fa-fw.fa-arrows
        span = suggestion

    = link_to_with_pagination('Previous', (params[:page].to_i - 1))
    br
    = link_to_with_pagination('Next', (params[:page].to_i + 1))

    h1 List of articles
    - @articles.each do |article|
      .panel.panel-default
      .panel-heading
        = link_to "#{article.title} | #{article.pmid}", "https://www.ncbi.nlm.nih.gov/pubmed/#{article.pmid}", target: "_blank"

      .panel-body
        - if article.date.present?
          = l(article.date, format: '%d/%B/%Y')
          br
        = article.abstract

app/views/searches/new.html.slim
h1.brand Biosearch Refinement

= render partial: 'form'